codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default: off
      python:
        flags: python
        target: auto
    patch:
      default: off
    changes: no

flags:
  python:
    paths:
      - src/rec4u