name: flake8 Lint
on: push
jobs:
  Status-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tonybajan/flake8-check-action@v1.0.0
        with:
          select: E3,E4,E5,E7,W6,F,B,G0
          repotoken: ${{ secrets.GITHUB_TOKEN }}